apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: guest-book-app
    name: guest-book
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: guest-book-app
    name: guest-book
